packages:
  - 0.12.1
  - latest

catalog:
  'turbo': ^2.3.3
  '@changesets/cli': ^2.27.10

  "@platforma-sdk/package-builder": "^3.2.3"
  "@platforma-sdk/blocks-deps-updater": "^2.0.0"

  "@platforma-open/milaboratories.runenv-java-corretto": "^1.1.7"
